C:\j2sdk1.4.0\bin\javac -classpath c:\jes;C:\j2sdk1.4.0;c:\;C:\j2sdk1.4.0\jre\lib\rt.jar;C:\j2sdk1.4.0\lib\tools.jar    Generation.java
C:\j2sdk1.4.0\bin\javac -classpath c:\jes;C:\j2sdk1.4.0;c:\;C:\j2sdk1.4.0\jre\lib\rt.jar;C:\j2sdk1.4.0\lib\tools.jar    Grafi.java
C:\j2sdk1.4.0\bin\javac -classpath c:\jes;C:\j2sdk1.4.0;c:\;C:\j2sdk1.4.0\jre\lib\rt.jar;C:\j2sdk1.4.0\lib\tools.jar    Session.java
C:\j2sdk1.4.0\bin\javac -classpath c:\jes;C:\j2sdk1.4.0;c:\;C:\j2sdk1.4.0\jre\lib\rt.jar;C:\j2sdk1.4.0\lib\tools.jar    ParamValue.java
C:\j2sdk1.4.0\bin\javac -classpath c:\jes;C:\j2sdk1.4.0;c:\;C:\j2sdk1.4.0\jre\lib\rt.jar;C:\j2sdk1.4.0\lib\tools.jar    Parameter.java
C:\j2sdk1.4.0\bin\javac -classpath c:\jes;C:\j2sdk1.4.0;c:\;C:\j2sdk1.4.0\jre\lib\rt.jar;C:\j2sdk1.4.0\lib\tools.jar    vectTableModel.java
C:\j2sdk1.4.0\bin\javac -classpath c:\jes;C:\j2sdk1.4.0;c:\;C:\j2sdk1.4.0\jre\lib\rt.jar;C:\j2sdk1.4.0\lib\tools.jar    Execution.java
C:\j2sdk1.4.0\bin\javac -classpath c:\jes;C:\j2sdk1.4.0;c:\;C:\j2sdk1.4.0\jre\lib\rt.jar;C:\j2sdk1.4.0\lib\tools.jar    MainGui.java
