c:\jdk1.3.1_01\bin\javac -classpath c:\jes;c:\jdk1.3.1_01;c:\;c:\jdk1.3.1_01\jre\lib\rt.jar;c:\jdk1.3.1_01\lib\tools.jar    Generation.java
c:\jdk1.3.1_01\bin\javac -classpath c:\jes;c:\jdk1.3.1_01;c:\;c:\jdk1.3.1_01\jre\lib\rt.jar;c:\jdk1.3.1_01\lib\tools.jar    Grafi.java
c:\jdk1.3.1_01\bin\javac -classpath c:\jes;c:\jdk1.3.1_01;c:\;c:\jdk1.3.1_01\jre\lib\rt.jar;c:\jdk1.3.1_01\lib\tools.jar    Session.java
c:\jdk1.3.1_01\bin\javac -classpath c:\jes;c:\jdk1.3.1_01;c:\;c:\jdk1.3.1_01\jre\lib\rt.jar;c:\jdk1.3.1_01\lib\tools.jar    ParamValue.java
c:\jdk1.3.1_01\bin\javac -classpath c:\jes;c:\jdk1.3.1_01;c:\;c:\jdk1.3.1_01\jre\lib\rt.jar;c:\jdk1.3.1_01\lib\tools.jar    Parameter.java
c:\jdk1.3.1_01\bin\javac -classpath c:\jes;c:\jdk1.3.1_01;c:\;c:\jdk1.3.1_01\jre\lib\rt.jar;c:\jdk1.3.1_01\lib\tools.jar    vectTableModel.java
c:\jdk1.3.1_01\bin\javac -classpath c:\jes;c:\jdk1.3.1_01;c:\;c:\jdk1.3.1_01\jre\lib\rt.jar;c:\jdk1.3.1_01\lib\tools.jar    Execution.java
c:\jdk1.3.1_01\bin\javac -classpath c:\jes;c:\jdk1.3.1_01;c:\;c:\jdk1.3.1_01\jre\lib\rt.jar;c:\jdk1.3.1_01\lib\tools.jar    MainGui.java

